go:
  image:
    goPackages:
      - mvdan.cc/gofumpt@latest

  fmt:
    formatter: gofumpt
    goimports:
      locals:
        - github.com/docker
        - github.com/eunomie/dague

  build:
    targets:
      local: &dague-build
        path: ./cmd/docker-dague
        env:
          CGO_ENABLED: 0
          GIT_COMMIT: shell git describe --tags | cut -c 2-
        ldflags: -s -w -X 'github.com/eunomie/dague/internal.Version=${GIT_COMMIT:-dev}'
      cross:
        << : *dague-build
        platforms:
          - linux/amd64
          - linux/arm64
          - darwin/amd64
          - darwin/arm64
          - windows/amd64
          - windows/arm64

tasks:
  install:
    deps:
      - go:build local
    cmds: |
      mkdir -p ~/.docker/cli-plugins
      install dist/docker-dague ~/.docker/cli-plugins/docker-dague
      echo Docker cli plugin installed, you can now use
      echo "    docker dague"

  refresh:
    deps:
      - go:fmt
      - go:doc
