go:
  image:
    src: golang:1.19.4-alpine3.17
    caches:
      - target: /cache/go
      - target: /go/pkg
    env:
      GOCACHE: /cache/go
      GOLANGCI_LINT_CACHE: /cache/go

  appDir: /go/src
  fmt:
    formatter: gofmt

  lint:
    govulncheck:
      enable: true
    golangci:
      enable: true
      image: golangci/golangci-lint:v1.50.1
