name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  godoc:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - name: dague-bin
        run: |
          gh release download --repo eunomie/dague --pattern docker-dague_linux_amd64 -O docker-dague
          chmod +x docker-dague
      - name: Check docs
        run: chmod +x ./docker-dague; ./docker-dague go:doc --check

  lint:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - name: dague-bin
        run: |
          gh release download --repo eunomie/dague --pattern docker-dague_linux_amd64 -O docker-dague
          chmod +x docker-dague
      - name: Lint
        run: chmod +x ./docker-dague; ./docker-dague go:lint

  format:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - name: dague-bin
        run: |
          gh release download --repo eunomie/dague --pattern docker-dague_linux_amd64 -O docker-dague
          chmod +x docker-dague
      - name: gofumpt
        run: chmod +x ./docker-dague; ./docker-dague go:fmt --check

  build-cross:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - name: dague-bin
        run: |
          gh release download --repo eunomie/dague --pattern docker-dague_linux_amd64 -O docker-dague
          chmod +x docker-dague
      - name: Find new version
        id: new_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # create a temporary tag for the build to get the right version
      - name: Tag
        run: git tag v${{ steps.new_version.outputs.new_version }}
      - name: Cross build binaries
        run: chmod +x ./docker-dague; ./docker-dague go:build cross
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: dague
          path: ./dist/

  release:
    runs-on: ubuntu-latest
    needs: [godoc, lint, format, build-cross]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Find new version
        id: new_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        if: github.event_name == 'push'
        with:
          name: dague
          path: dist
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          makeLatest: true
          prerelease: false
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.new_version.outputs.new_version }}
          body: ${{ steps.new_version.outputs.changelog }}
