name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: bootstrap binary
        run: go build -o docker-dague ./cmd/docker-dague
      - uses: actions/upload-artifact@v3
        with:
          name: dague-bin
          path: ./docker-dague

  godoc:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: actions/download-artifact@v2
        with:
          name: dague-bin
      - name: Check docs
        run: chmod +x ./docker-dague; ./docker-dague dague go:doc --check

  govuln:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: actions/download-artifact@v2
        with:
          name: dague-bin
      - name: Check govuln
        run: chmod +x ./docker-dague; ./docker-dague dague lint:govuln

  gofumpt:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: actions/download-artifact@v2
        with:
          name: dague-bin
      - name: gofumpt
        run: chmod +x ./docker-dague; ./docker-dague dague fmt:print

  build-cross:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: actions/download-artifact@v2
        with:
          name: dague-bin
      - name: Find new version
        id: new_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cross build binaries
        run: chmod +x ./docker-dague; ./docker-dague dague go:cross --ldflags="-X 'github.com/eunomie/dague/internal.Version=${{ steps.new_version.outputs.new_version }}'" ./cmd/docker-dague
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: dague
          path: ./dist/

  release:
    runs-on: ubuntu-latest
    needs: [godoc, govuln, gofumpt, build-cross]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Find new version
        id: new_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.new_version.outputs.new_version }}
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        if: github.event_name == 'push'
        with:
          name: dague
          path: dist
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.new_version.outputs.new_version }}
          body: ${{ steps.new_version.outputs.changelog }}
