name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  govuln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install mage
        run: go install github.com/magefile/mage
      - name: govulncheck
        run: mage -d hack lint:govuln

  gofumpt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install mage
        run: go install github.com/magefile/mage
      - name: govulncheck
        run: mage -d hack gofumpt:print

  build-cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install mage
        run: go install github.com/magefile/mage
      - name: govulncheck
        run: mage -d hack go:cross ./cmd/dague
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: dague
          path: ./dist/

  docker:
    runs-on: ubuntu-latest
    needs: [govuln, gofumpt, build-cross]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Find the new version first, and only create the tag when the image has been built and pushed
      - name: Find new version
        id: new_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          dry_run: true
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eunomie/dague
          tags: |
            type=semver,pattern={{version}},value=${{steps.new_version.outputs.new_tag}}
            type=semver,pattern={{major}}.{{minor}},value=${{steps.new_version.outputs.new_tag}}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Tag version
        if: github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.new_version.outputs.new_version }}
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        if: github.event_name == 'push'
        with:
          path: dist
      - name: Create a GitHub release
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.new_version.outputs.new_version }}
          body: ${{ steps.new_version.outputs.changelog }}
